name: omagines_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  serverpod: ^0.9.19
  serverpod_cloud_storage_s3: ^0.9.19

dev_dependencies:
  lints: ^2.0.0
